eureka:
  instance:
    hostname: email-service
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://admin:admin@discovery-service:8761/eureka/
    register-with-eureka: false
    fetch-registry: false