greeting:
  message: Hello!
  
app:
  name: Boot App
  description: This is ${app.name}

my:
  list:
    values: value1, value2, value3
    
  map:
    values: "{param1: 'value1', param2: 'value2', param3: 'value3'}"

db:
  connection: "{connectionString: 'https://_____', username: 'testuser', password: 'testpass'}"
  host: testsrv
  port: 9912

management:
  endpoints:
    web:
      exposure:
        include: "*"